import { CSSProperties } from 'react';

const ivyPrismTheme: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: '1em',
    background: 'transparent',
    color: '#061109',
  },
  'pre[class*="language-"]': {
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: '1em',
    background: 'transparent',
    padding: '1em',
    margin: 0,
    color: '#061109',
    overflow: 'auto',
    border: '1px solid #C0CCC8',
    borderRadius: '0.5em',
  },
  comment: { color: '#6a9955', fontStyle: 'italic' },
  string: { color: '#05986A' },
  number: { color: '#061109' },
  boolean: { color: '#8030AF' },
  keyword: { color: '#8030AF' },
  function: { color: '#0000FF' },
  className: { color: '#0000FF' },
  operator: { color: '#061109' },
  punctuation: { color: '#061109' },
  tag: { color: '#8030AF' },
  attrName: { color: '#0000FF' },
  attrValue: { color: '#05986A' },
  plain: { color: '#061109' },
  // HTML specific tokens
  'tag.tag': { color: '#8030AF' },
  'tag.attr-name': { color: '#0000FF' },
  'tag.attr-value': { color: '#05986A' },
  'tag.punctuation': { color: '#061109' },
  // CSS specific tokens
  property: { color: '#0000FF' },
  selector: { color: '#8030AF' },
  'selector.class': { color: '#0000FF' },
  'selector.id': { color: '#0000FF' },
  'selector.pseudo-class': { color: '#8030AF' },
  'selector.pseudo-element': { color: '#8030AF' },
  unit: { color: '#061109' },
  color: { color: '#05986A' },
  'function.function': { color: '#0000FF' },
  'function.url': { color: '#05986A' },
  // JSON specific tokens
  'property.string': { color: '#0000FF' },
  'property.number': { color: '#0000FF' },
  'property.boolean': { color: '#0000FF' },
  'property.null': { color: '#0000FF' },
  // Additional tokens for better coverage
  variable: { color: '#0000FF' },
  constant: { color: '#8030AF' },
  symbol: { color: '#8030AF' },
  deleted: { color: '#d73a49' },
  inserted: { color: '#05986A' },
  changed: { color: '#f6a434' },
  important: { color: '#d73a49', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
  entity: { color: '#0000FF' },
  url: { color: '#05986A' },
  atrule: { color: '#8030AF' },
  rule: { color: '#8030AF' },
  regex: { color: '#05986A' },
  prolog: { color: '#6a9955' },
  doctype: { color: '#6a9955' },
  cdata: { color: '#6a9955' },
  namespace: { color: '#6a9955' },
  builtin: { color: '#0000FF' },
  char: { color: '#05986A' },
  directive: { color: '#8030AF' },
  'directive.tag': { color: '#8030AF' },
  'directive.attr-name': { color: '#0000FF' },
  'directive.attr-value': { color: '#05986A' },
  'directive.punctuation': { color: '#061109' },
};

export default ivyPrismTheme;
